on:
  push:
    branches:    
      - '44-game'

jobs:
  game:
    name: Wild Guess
    runs-on: ubuntu-latest

    # if: startsWith(github.event.issue.title, 'And I guess (0-9):')

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      # - name: Set env vars
      #   run: |
      #       echo "USERNAME=${{ github.event.issue.user.login }}" >> $GITHUB_ENV
      #       echo "ISSUE_TITLE=${{ github.event.issue.title }}" >> $GITHUB_ENV

      - name: Updating README.md
        id: wild_guess
        run: |
            echo "$TITLE $NAME $URL"
            bash scripts/game.sh "$ISSUE_TITLE" "$USERNAME"


      - name: Guessed NaN
        if: ${{ failure() }}
        run: echo ${{ toJSON(steps.wild_guess) }}