name: CI

on:
  push:
    branches:    
      - '44-game'

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest

    outputs:
      code: ${{ steps.set-code.outputs.code }}

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: hlo
        id: set-code
        run: |
          echo "code=$(bash scripts/game.sh 'And I guess (0-9): 7' 'tanishq-singh-2301')" >> $GITHUB_OUTPUT


      # - name: hello
      #   uses: actions-cool/issues-helper@v3
      #   with:
      #     actions: 'update-issue'
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     issue-number: 45
      #     state: 'closed'
      #     update-mode: 'append'
      #     labels: 'Guessed NaN,wild guess'
      #     body: |

      #       You entered NaN,
      #       Please enter a number between 0 and 9, refer above.

  job2:
    needs: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: echo ${{ needs.CI.outputs.code }}
