name: CI

on:
  push:
    branches:    
      - '44-game'

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: hello
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'update-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: 45
          state: 'closed'
          update-mode: 'append'
          labels: 'Guessed NaN,wild guess'
          body: |
            \n\n
            You entered NaN,
            Please enter a number between 0 and 9, refer above.
